version: '3'

services:
  db:
    image: 'bitnami/postgresql:latest'
    container_name: 'postgres_exp_tracker'
    networks:
      - app-tier
    env_file:
      - postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgresql_master_data:/bitnami/postgresql
  app:
    image: 'exp-tracker-api'
    container_name: 'exp_tracker_api'
    networks:
      - app-tier
    env_file:
      - app.env
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgresql_master_data:
networks:
  app-tier:
    driver: bridge